micronaut:
  application:
    name: scoringdatagenerator
  server:
    port: 8090
netty:
  default:
    allocator:
      max-order: 3

kafka:
  database:
    host: localhost
    port: 8088
  bootstrap:
    servers: localhost:29092

application:
  events:
    enabled: true

